config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
	
	resources :employees

	root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	before_action :all_employees, only: [:index, :create]
	before_action :set_employees, only: [:edit, :update]
  respond_to :html, :js
	
	def create
		@employee = Employee.new(employee_params)

		@employee.save
	end
		
	def new
		@employee = Employee.new
	end
	
	def edit
		@employee = Employee.find(params[:id])
	end
	
	def show
		@employee = Employee.find(params[:id])
	end
	
	def update
		@employee.update(employee_params)
	end
	
	def destroy
		@employee = Employee.find(params[:id])
		@employee.destroy

		redirect_to employees_path
	end
	
	private
		def employee_params
			params.require(:employee).permit(:name, :salary)
		end
	
		def all_employees
			@employees = Employee.all
			@totalsalary = 0
			@employees.each do |employee|
				@totalsalary += employee.salary
			end
		end
	
		def set_employees
      @employee = Employee.find(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/employees/_employee.html.erb
<%= div_for employee do %>

  <h3><%= employee.name %></h3>
	<h4>Salario: <%= employee.salary %></h4>

  <ul>
   <li><%= link_to "Edit Employee", edit_employee_path(employee), remote: true %></li>
   <li><%= link_to "Delete Employee", employee, remote: true, method: :delete %></li>
  </ul>
	<hr>
<% end %>

app/views/employees/_form.html.erb
<%= form_for(@employee, remote: true) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :salary %><br>
    <%= f.number_field :salary %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/employees/create.js.erb
$('form').hide();
$('#employees').append('<%= j render partial: "employee", locals: {employee: @employee} %>');

app/views/employees/destroy.js.erb
$('div#<%= dom_id(@employee) %>').fadeOut();

app/views/employees/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', employees_path %>

app/views/employees/edit.js.erb
$('#employee-form').html("<%= j (render 'form') %>");
$('#employee-form').slideDown(350);

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<%= link_to 'New employee', new_employee_path, :remote => true %>

<div id="employee-form" style="display:none;"></div>

<div id="totalsalary"></div>

<div id="employees"><%= render @employees %></div>

app/views/employees/new.html.erb
<h1>New employee</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', employees_path %>

app/views/employees/new.js.erb
$('#employee-form').html("<%= j (render 'form') %>");
$('#employee-form').slideDown(350);

app/views/employees/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>
 
<p>
  <strong>Salary:</strong>
  <%= @employee.salary %>
</p>
<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/employees/update.js.erb
$('form').hide();
$('div#<%= dom_id(@employee) %>').replaceWith('<%= j render partial: "employee", locals: {employee: @employee} %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapplication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>